# Generated by Django 5.1.6 on 2025-02-25 06:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busCompany', models.CharField(max_length=20)),
                ('busNo', models.PositiveIntegerField(default=1, unique=True)),
                ('availableSeats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('fromWhere', models.CharField(max_length=20)),
                ('toWhere', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(max_length=20, unique=True)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketId', models.IntegerField(unique=True)),
                ('busNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenBus_App.busmodel')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenBus_App.usermodel')),
            ],
        ),
    ]
