# Generated by Django 5.1.6 on 2025-03-03 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
