# Generated by Django 5.1.6 on 2025-02-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmodel',
            name='dateAndTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
