# Generated by Django 5.1.6 on 2025-03-03 09:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0002_remove_usermodel_age_remove_usermodel_customerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmodel',
            name='blockedSeats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
    ]
