# Generated by Django 5.1.6 on 2025-02-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0002_busmodel_dateandtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busmodel',
            name='dateAndTime',
            field=models.DateTimeField(),
        ),
    ]
