# Generated by Django 5.1.6 on 2025-02-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0003_alter_busmodel_dateandtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busmodel',
            old_name='dateAndTime',
            new_name='boardingTIme',
        ),
    ]
