# Generated by Django 5.1.6 on 2025-03-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0003_busmodel_blockedseats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companymodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='routemodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='companymodel',
            table='Bus Company',
        ),
        migrations.AlterModelTable(
            name='routemodel',
            table='Bus Routes',
        ),
    ]
