# Generated by Django 5.1.6 on 2025-02-25 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0004_rename_dateandtime_busmodel_boardingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busmodel',
            name='boardingTIme',
            field=models.CharField(choices=[('Morning', '9am'), ('Night', '9pm')]),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.CharField(max_length=20)),
                ('paymentStatus', models.CharField(choices=[('Paid', 'Successful'), ('Not Paid', 'Not Successful')])),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenBus_App.usermodel')),
                ('ticketId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenBus_App.ticketmodel')),
            ],
        ),
    ]
