# Generated by Django 5.1.6 on 2025-03-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0005_alter_routemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routemodel',
            options={'ordering': ['bus']},
        ),
    ]
