# Generated by Django 5.1.6 on 2025-02-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0005_alter_busmodel_boardingtime_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.CharField(max_length=20, unique=True)),
                ('paymentStatus', models.CharField(choices=[('Paid', 'Successful'), ('Not Paid', 'Not Successful')])),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenBus_App.usermodel')),
                ('ticketId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenBus_App.ticketmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
