# Generated by Django 5.1.6 on 2025-03-04 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0006_alter_routemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='seatNumbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
