# Generated by Django 5.1.6 on 2025-02-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0006_paymentmodel_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='paymentStatus',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], default='Not Paid'),
        ),
    ]
