# Generated by Django 5.1.6 on 2025-02-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0007_alter_paymentmodel_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='paymentStatus',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=10),
        ),
    ]
