# Generated by Django 5.1.6 on 2025-02-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0008_alter_paymentmodel_paymentstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='bookingId',
        ),
    ]
