# Generated by Django 5.1.6 on 2025-02-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0009_remove_paymentmodel_bookingid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busmodel',
            old_name='boardingTIme',
            new_name='boardingTime',
        ),
    ]
