# Generated by Django 5.1.6 on 2025-02-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0010_rename_boardingtime_busmodel_boardingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busmodel',
            name='boardingTime',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Night', 'Night')]),
        ),
    ]
