# Generated by Django 5.1.6 on 2025-02-25 09:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0012_alter_busmodel_boardingtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='seatSelected',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
