# Generated by Django 5.1.6 on 2025-02-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0013_ticketmodel_seatselected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmodel',
            old_name='customerId',
            new_name='customerName',
        ),
    ]
