# Generated by Django 5.1.6 on 2025-02-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0014_rename_customerid_ticketmodel_customername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='customerId',
            new_name='customerName',
        ),
        migrations.RenameField(
            model_name='ticketmodel',
            old_name='busNo',
            new_name='busCompany',
        ),
    ]
