# Generated by Django 5.1.6 on 2025-02-25 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0015_rename_customerid_paymentmodel_customername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmodel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
