# Generated by Django 5.1.6 on 2025-02-26 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0016_busmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busCompany', models.CharField(max_length=20)),
                ('noOfBuses', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='busmodel',
            name='busCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenBus_App.companymodel'),
        ),
    ]
