# Generated by Django 5.1.6 on 2025-02-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0017_companymodel_alter_busmodel_buscompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmodel',
            old_name='busCompany',
            new_name='busNo',
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='noOfBuses',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
