# Generated by Django 5.1.6 on 2025-02-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0018_rename_buscompany_ticketmodel_busno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busmodel',
            name='perSeatPrice',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='ticket_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
