# Generated by Django 5.1.6 on 2025-02-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0019_busmodel_perseatprice_ticketmodel_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='paymentStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticket_price',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
