# Generated by Django 5.1.6 on 2025-02-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0020_alter_paymentmodel_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='ticketId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GreenBus_App.ticketmodel'),
        ),
    ]
