# Generated by Django 5.1.6 on 2025-02-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0021_ticketmodel_status_alter_paymentmodel_ticketid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmodel',
            name='status',
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='ticketId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GreenBus_App.ticketmodel'),
        ),
    ]
