# Generated by Django 5.1.6 on 2025-02-26 11:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0022_remove_ticketmodel_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRouteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeName', models.CharField(max_length=100, unique=True)),
                ('stops', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='RouteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopName', models.CharField(max_length=50)),
                ('stopOrder', models.PositiveIntegerField()),
                ('bookedSeats', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='GreenBus_App.busmodel')),
            ],
            options={
                'ordering': ['stopOrder'],
            },
        ),
    ]
