# Generated by Django 5.1.6 on 2025-02-26 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0025_delete_busroutemodel_routemodel_bookedseats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busmodel',
            name='availableSeats',
        ),
        migrations.RemoveField(
            model_name='routemodel',
            name='bookedSeats',
        ),
        migrations.CreateModel(
            name='SeatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='GreenBus_App.busmodel')),
            ],
            options={
                'unique_together': {('bus', 'seat_number')},
            },
        ),
        migrations.AddField(
            model_name='routemodel',
            name='bookedSeats',
            field=models.ManyToManyField(blank=True, to='GreenBus_App.seatmodel'),
        ),
    ]
