# Generated by Django 5.1.6 on 2025-02-26 12:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0026_remove_busmodel_availableseats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routemodel',
            name='bookedSeats',
        ),
        migrations.AddField(
            model_name='busmodel',
            name='availableSeats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='busmodel',
            name='bookedSeats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='busmodel',
            name='totalSeats',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.DeleteModel(
            name='SeatModel',
        ),
        migrations.AddField(
            model_name='routemodel',
            name='bookedSeats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
    ]
