# Generated by Django 5.1.6 on 2025-02-27 04:57

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenBus_App', '0027_remove_routemodel_bookedseats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketmodel',
            old_name='busNo',
            new_name='bus',
        ),
        migrations.RenameField(
            model_name='ticketmodel',
            old_name='customerName',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='ticketmodel',
            old_name='ticket_price',
            new_name='ticketPrice',
        ),
        migrations.RemoveField(
            model_name='ticketmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ticketmodel',
            name='seatSelected',
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='bookingDate',
            field=models.DateField(auto_now_add=True, default='2025-02-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='fromStop',
            field=models.CharField(default=datetime.datetime(2025, 2, 27, 4, 56, 54, 470754, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='seatNumbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='toStop',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ticketId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
